### ISSUE TITLE
Number of DNA replicates not equal to RNA replicates

### ISSUE THREAD

**Issue by shubhamkhetan** [hansenlab/mpra#3]
I apologize if this is obvious, but I haven't been able to figure it out: how do I create an MPRASet if the number of DNA replicates is not equal to the number of RNA replicates? In all the examples, the number of replicates for DNA and RNA are assumed to be the identical, which is not always the case. Thank you.

**Comment by lmyint** [comment]
You'll need to make the DNA count matrix have the same number of columns as the RNA count matrix. I understand that if you only measure DNA pre-transfection, you may not have the same number of replicates as for RNA. (We feel that measuring DNA post-transfection gives a better picture of MPRA element activity due to imperfect transfection efficiency.)
Every cell in the RNA count matrix needs to have an associated DNA count in order for activity measures to be contributed. So if DNA replicate 1 is linked to RNA replicates 1 and 2, you would need to repeat the first DNA count column twice.

**Comment by shubhamkhetan** [comment]
Thank you. 
I agree, measuring DNA post-transfection would be the ideal scenario. However, it is difficult (although not impossible) to obtain both plasmids and RNA from the same sample.
