### ISSUE TITLE
can you provide input file example

### ISSUE THREAD

**Issue by bioarpit1** [hansenlab/mpra#4]
Hi I am very new to MPRA analysis. If you can provide the input file example to create MPRAset that would be very helpful. currently I have element b_arcode + count information as csv file. I am not sure how to create MPRAset from that. 

Thanks

Arpit

**Comment by lmyint** [comment]
Because there is such a wide variety of file formats for these assays, we don't have a description of file I/O in our [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/mpra/inst/doc/mpra.html) (or functionality within the package to directly create `MPRASets` from file), but the vignette is a good place to check what the `mpra` package expects the count matrices to look like.

An example input file for DNA counts could be a CSV file. Rows in the CSV file would correspond to the individual elements assayed, and columns would correspond to samples. I recommend that the first column of the CSV file be an `element_id` column. The remaining S columns would give the DNA counts for each element in each of the S samples.

The same structure of input file would work for the RNA counts.

Note that if you read in these CSV files, the objects will be `data.frame`'s rather than matrices, which are the expected type for creating an `MPRASet`, so if you went this route, you'd have to subset out the counts from the `data.frame`'s and cast them to matrices.

**Comment by bioarpit1** [comment]
Thanks for the response i have updated my input now it looks like this 
![image](https://user-images.githubusercontent.com/29548776/92067813-185fea00-ed5a-11ea-979f-53b00ba3ed98.png)
this matches the input given in vignette, now i have some more question 
1. i have three replicates in each replicate unique elements detected varies a bit (7886, 7933, 7992) so for E what values should i use ? 
2.  also for nalleles i have mostly two alleles but they can be anything A, T , G or C so should i give nalleles as 4 ? 

i am wetlab scientist trying to run this so sorry for my silly questions 
i have used this command is it correct based on the given information 
![image](https://user-images.githubusercontent.com/29548776/92068098-d7b4a080-ed5a-11ea-87c6-40b8a0242532.png)

**Comment by lmyint** [comment]
No need to apologize for the questions. If the number of unique elements detected varies from replicate to replicate, you should include NAs in your CSV file for elements that are undetected in a replicate.

If you have a different number of alleles for different SNPs (e.g., mostly 2 alleles, but sometimes 3 or 4), then currently this package does not implement the functionality to handle the varying numbers of alleles. While this functionality is planned to be included in the package in the future, for now, the number of comparisons per element (# comparisons = # alleles) needs to be equal across elements (e.g., keeping all the 2-allele elements and for elements with 3+ alleles, picking the two main alleles of interest to compare).

It's hard to tell from just your screenshot whether the code is fully correct, but I do see something that is incorrect in the code: `elem_id` within the `lapply` is using the numbers 1,2,...,E, but this is not pulling out the correct rows of your count data because the names of your elements have longer numbers as identifiers.

It's difficult to help with coding problems like this in this format. I would suggest finding a bioinformatics collaborator at your institution who can help with this.
